"""add category to book

Revision ID: 6d95b7155f7c
Revises: 65b0395711ab
Create Date: 2026-04-01 15:40:52.399197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d95b7155f7c'
down_revision = '65b0395711ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=20), nullable=True))

    op.execute("UPDATE book SET category = 'fiction' WHERE category IS NULL")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
