"""add want-to-read and reading progress fields

Revision ID: f3d98dace91c
Revises: f7faf9c590e4
Create Date: 2026-03-31 23:28:43.407395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3d98dace91c'
down_revision = 'f7faf9c590e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False, server_default='read'))
        batch_op.add_column(sa.Column('date_added', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('cover_url', sa.Text(), nullable=True))
        batch_op.alter_column('sentiment',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('position',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('google_books_url',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reading_goal', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('reading_goal')

    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.alter_column('google_books_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)
        batch_op.alter_column('position',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('sentiment',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.drop_column('cover_url')
        batch_op.drop_column('date_added')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
